remote_theme: engraver/bay

title: Oleksandr V. Pylypovskyi
description: Home page of Oleksandr V. Pylypovskyi
#og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Bio
    - name: Research
    - name: Teaching
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: o.pylypovskyi/att/hzdr.de
      link: mailto:o.pylypovskyi/att/hzdr.de
#    - name: WeChat
#      value: YourWeChatUsername
#      link: "#"
#  follow:
#    - name: Twitter
#      link: http://twitter.com/YourTwitterUsername
#      username: "@YourTwitterUsername"
#    - name: Facebook
#      link: http://facebook.com/YourFacebookUsername
#    - name: LinkedIn
#      link: http://linkedin.com/in/YourLinkedInUsername
#    - name: GitLab
#      link: http://github.com/YourGitHubUsername
#    - name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - name: RSS
#      link: /feed.xml

# Build settings
markdown: kramdown
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
sass:
    style: :compressed
plugins:
  - jekyll-feed

#output:
#  html_document:
#    includes:
#      in_header: ga.html
